-- ============================================================
-- 05_create_raw_tables.sql
-- PURPOSE : Create the raw tables that receive synthetic
--           clickstream data from Kafka via Snowpipe.
-- RUN     : snowsql -f bronze/05_create_raw_tables.sql
-- ORDER   : Run AFTER 04_create_raw_stages.sql
--
-- NOTE: These tables are NOT clones — they receive new data
-- generated by our Python Faker scripts. They complement the
-- TPC-DS clones by adding a streaming clickstream dimension
-- that TPC-DS doesn't natively provide.
-- ============================================================

USE DATABASE  RETAIL_DB;
USE SCHEMA    RETAIL_DB.BRONZE;
USE WAREHOUSE RETAIL_WH;

-- ── raw_clickstream ───────────────────────────────────────────
-- Receives JSON messages from the retail.clickstream Kafka topic.
-- Each row = one user event on the website.
--
-- Fields:
--   session_id     : UUID grouping all events in one browser session
--   user_id        : customer identifier (maps to TPC-DS customer)
--   item_id        : product the event relates to (maps to TPC-DS item)
--   event_type     : page_view | add_to_cart | purchase
--   event_timestamp: when the event occurred (UTC)
--   device_type    : desktop | mobile | tablet
--   referrer_source: organic | paid_search | email | social | direct
--   _ingested_at   : when Snowpipe loaded this row (audit column)
CREATE TABLE IF NOT EXISTS BRONZE.raw_clickstream (
    session_id       VARCHAR(64)      NOT NULL,
    user_id          NUMBER(38, 0),
    item_id          NUMBER(38, 0),
    event_type       VARCHAR(20)      NOT NULL,
    event_timestamp  TIMESTAMP_NTZ    NOT NULL,
    device_type      VARCHAR(20),
    referrer_source  VARCHAR(30),
    _ingested_at     TIMESTAMP_NTZ    DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Raw clickstream events from Kafka via Snowpipe — append only';
